namespace: mesh
name: element
version: 1.0.0
readme: README.md
authors:
- Carlos Simon <casimon@redhat.com>
description: Deploy mesh elements
license:
- GPL-2.0-or-later
license_file: ''
tags: []
dependencies:
  kubernetes.core: ">=2.4.0"

repository: https://github.com/casimon-rh/ansible-mesh-element
documentation: http://docs.example.com

build_ignore: []


