---
- name: auth_ocp
  kubernetes.core.k8s_auth:
    host: "{{ openshift_url }}"
    username: "{{ openshift_username }}"
    password: "{{ openshift_password }}"
    validate_certs: "{{ openshift_valcerts }}"
  register: ocp_auth_results
- name: helm gw
  kubernetes.core.helm:
    host: "{{ openshift_url }}"
    api_key: "{{ocp_auth_results.k8s_auth.api_key}}"
    validate_certs: "{{ openshift_valcerts }}"
    chart_repo_url: "{{ helmchart_url }}"
    chart_ref: "{{ helmchart_ref }}"
    chart_version: "{{ helmchart_version }}"
    release_name: "{{ item.name }}"
    release_namespace: "{{ helmchart_namespace }}"
    release_values: "{{ lookup('template', 'valuesgw.yaml.tpl') | from_yaml }}"
    state: "{{ helmchart_state }}"
  loop: "{{ helmchart_gwelement }}"
  loop_control:
    label: "{{ item.name }}"
- name: helm gw
  kubernetes.core.helm:
    host: "{{ openshift_url }}"
    api_key: "{{ocp_auth_results.k8s_auth.api_key}}"
    validate_certs: "{{ openshift_valcerts }}"
    chart_repo_url: "{{ helmchart_url }}"
    chart_ref: "{{ helmchart_ref }}"
    chart_version: "{{ helmchart_version }}"
    release_name: "{{ item.name }}"
    release_namespace: "{{ helmchart_namespace }}"
    release_values: "{{ lookup('template', 'values.yaml.tpl') | from_yaml }}"
    state: "{{ helmchart_state }}"
  loop: "{{ helmchart_elements }}"
  loop_control:
    label: "{{ item.name }}"